#! /usr/bin/env bash

## curl -L https://raw.githubusercontent.com/jmmk/osx-workstation/master/bootstrap | bash

set -eo pipefail

readonly REPO_DIR="$HOME/osx-workstation"

log() {
  echo "Bootstrap: $1"
}

check-exists() {
  hash $1 &> /dev/null
}

main() {
  if ! $(check-exists brew); then
    log "Install homebrew"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [[ -z $(brew list | grep "^git$") ]]; then
    log "Install git from homebrew"
    brew install git
  fi

  log "Get latest provisioning code"
  if [[ ! -d "$REPO_DIR" ]]; then
    git clone -q --depth 1 git@github.com:jmmk/osx-workstation "$REPO_DIR"
  else
    cd "$REPO_DIR" && git pull -q origin master
  fi

  if ! $(check-exists brew); then
    log "Install planck"
    brew install planck
  fi

  log "Complete"
  planck -s . -m provision.core
}

main "$@"
